# Generated by Django 5.0.1 on 2024-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algaebackend', '0002_llm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='access_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
