# Generated by Django 5.0.1 on 2024-01-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algaebackend', '0003_llm_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llm',
            name='access_token',
        ),
    ]
