# Generated by Django 5.0.1 on 2024-01-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algaebackend', '0005_document_documentfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_id',
            new_name='user',
        ),
    ]
