# Generated by Django 5.0.7 on 2025-12-06 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algaebackend", "0009_chatsession_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_handling_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time to get/create session and load history",
                    ),
                ),
                (
                    "vector_search_ms",
                    models.IntegerField(
                        default=0, help_text="Time for Pinecone vector search"
                    ),
                ),
                (
                    "entity_extraction_ms",
                    models.IntegerField(
                        default=0, help_text="Time for LLM entity extraction"
                    ),
                ),
                (
                    "graph_expansion_ms",
                    models.IntegerField(
                        default=0, help_text="Time for Neo4j graph traversal"
                    ),
                ),
                (
                    "llm_generation_ms",
                    models.IntegerField(
                        default=0, help_text="Time for final answer generation"
                    ),
                ),
                (
                    "total_ms",
                    models.IntegerField(
                        default=0, help_text="Total request processing time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_metrics",
                        to="algaebackend.chatmessage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Response metrics",
                "ordering": ["-created_at"],
            },
        ),
    ]
